# Generated by Django 2.2.12 on 2020-11-26 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20201126_1932'),
    ]

    operations = [
    ]
