# Generated by Django 2.2.12 on 2020-11-26 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20201126_1938'),
    ]

    operations = [
    ]
