# Generated by Django 2.2.12 on 2020-11-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20201126_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingadd',
            old_name='Shipping',
            new_name='shipping',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(default=92121, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shippingadd',
            name='id',
            field=models.CharField(default=25640, max_length=10, primary_key=True, serialize=False),
        ),
    ]
