# Generated by Django 2.2.12 on 2020-12-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_lastlogin_lougout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lastlogin',
            old_name='lougout',
            new_name='logout',
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
