# Generated by Django 2.2.12 on 2020-12-02 13:00

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_lastlogin_logout'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex/Parody')], default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingadd',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
