# Generated by Django 2.2.12 on 2020-12-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_auto_20201202_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Motors', 'Motors'), ('Books, Movies & Music', 'Books, Movies & Music'), ('Electronics', 'Electronics'), ('Collectibles & Art', 'Collectibles & Art'), ('Fashion', 'Fashion'), ('Home & Garden', 'Home & Garden'), ('Sporting Goods', 'Sporting Goods'), ('Toys & Hobbies', 'Toys & Hobbies'), ('Business & Industrial', 'Business & Industrial'), ('Health & Beauty', 'Health & Beauty'), ('Others', 'Others')], default='null', max_length=100),
        ),
    ]
