# Generated by Django 2.2.12 on 2020-12-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_auto_20201203_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='null', upload_to=''),
            preserve_default=False,
        ),
    ]
