# Generated by Django 2.2.12 on 2020-12-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_auto_20201203_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='permission_Level',
        ),
        migrations.AddField(
            model_name='seller',
            name='store_name',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
