# Generated by Django 2.2.12 on 2020-12-03 19:32

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_auto_20201203_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Motors', 'Motors'), ('Books, Movies & Music', 'Books, Movies & Music'), ('Electronics', 'Electronics'), ('Collectibles & Art', 'Collectibles & Art'), ('Fashion', 'Fashion'), ('Home & Garden', 'Home & Garden'), ('Sporting Goods', 'Sporting Goods'), ('Toys & Hobbies', 'Toys & Hobbies'), ('Business & Industrial', 'Business & Industrial'), ('Health & Beauty', 'Health & Beauty'), ('Others', 'Others')], default='Others', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=django_ckeditor_5.fields.CKEditor5Field(default='null', verbose_name='product_description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('False', 'Not Active'), ('True', 'Active')], default='Not Active', max_length=10),
        ),
    ]
