# Generated by Django 2.2.12 on 2020-12-05 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_auto_20201205_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='Buyer',
        ),
    ]
