# Generated by Django 2.2.12 on 2020-12-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_remove_seller_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='store_category',
            field=models.CharField(choices=[('Motors', 'Motors'), ('Books, Movies & Music', 'Books, Movies & Music'), ('Electronics', 'Electronics'), ('Collectibles & Art', 'Collectibles & Art'), ('Fashion', 'Fashion'), ('Home & Garden', 'Home & Garden'), ('Sporting Goods', 'Sporting Goods'), ('Toys & Hobbies', 'Toys & Hobbies'), ('Business & Industrial', 'Business & Industrial'), ('Health & Beauty', 'Health & Beauty'), ('Others', 'Others')], default='Others', max_length=100),
        ),
    ]
