# Generated by Django 2.2.12 on 2020-12-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0058_seller_store_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.IntegerField(default=0, max_length=1000000),
        ),
    ]
