# Generated by Django 2.2.12 on 2020-12-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0064_auto_20201209_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactbuyer',
            name='reciever',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='contactseller',
            name='reciever',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
