# Generated by Django 2.2.12 on 2020-12-09 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0065_auto_20201209_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactbuyer',
            old_name='reciever',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='contactseller',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
