# Generated by Django 2.2.12 on 2020-12-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0068_wishlist_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product_name',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
