# Generated by Django 2.2.12 on 2020-12-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0077_auto_20201213_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactseller',
            name='receiver',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
