# Generated by Django 2.2.12 on 2020-12-13 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0082_auto_20201213_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('discount_amount', models.FloatField(default=0)),
                ('title', models.CharField(default='null', max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('Seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Seller')),
            ],
        ),
    ]
