# Generated by Django 2.2.12 on 2020-12-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0083_coupons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='status',
            field=models.CharField(choices=[('False', 'Not Active'), ('True', 'Active')], default='Not Active', max_length=100),
        ),
    ]
