# Generated by Django 2.2.12 on 2020-12-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0087_auto_20201214_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsite',
            name='message_category',
            field=models.CharField(choices=[('Fraud', 'Fraud'), ('Bugs', 'Bugs'), ('Exploits', 'Exploits'), ('Business', 'Business'), ('General', 'General'), ('Collaborations', 'Collaborations'), ('Jobs', 'Jobs')], default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='contactsite',
            name='priority',
            field=models.CharField(choices=[('Critical', 'Critical'), ('Urgent', 'Urgent'), ('Important', 'Important'), ('Normal', 'Normal')], default='Normal', max_length=100),
        ),
    ]
