# Generated by Django 2.2.12 on 2020-12-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0089_remove_contactsite_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='productRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='null', max_length=200)),
                ('body_text', models.TextField(default='null', max_length=2000)),
                ('name', models.CharField(default='null', max_length=200)),
                ('email', models.EmailField(default='null', max_length=200)),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=100)),
            ],
        ),
    ]
