# Generated by Django 2.2.12 on 2020-12-14 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0092_auto_20201214_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrating',
            old_name='product',
            new_name='Product',
        ),
    ]
