# Generated by Django 2.2.12 on 2020-12-15 18:59

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0096_auto_20201215_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='followers',
            field=models.IntegerField(default=80623),
        ),
        migrations.CreateModel(
            name='storeRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('rating', models.CharField(default='1', max_length=100)),
                ('name', models.CharField(default='null', max_length=200)),
                ('email', models.EmailField(default='null', max_length=200)),
                ('title', models.CharField(default='null', max_length=200)),
                ('Description', django_ckeditor_5.fields.CKEditor5Field(default='null', verbose_name='Description')),
                ('Seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Seller')),
            ],
        ),
    ]
