# Generated by Django 2.2.12 on 2020-12-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0097_auto_20201215_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='randomImageNumber',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='seller',
            name='followers',
            field=models.IntegerField(default=61139),
        ),
    ]
