# Generated by Django 2.2.12 on 2020-12-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0101_auto_20201215_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrating',
            name='title',
        ),
        migrations.RemoveField(
            model_name='storerating',
            name='title',
        ),
        migrations.AlterField(
            model_name='productrating',
            name='randomImageNumber',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='seller',
            name='followers',
            field=models.IntegerField(default=87122),
        ),
        migrations.AlterField(
            model_name='storerating',
            name='randomImageNumber',
            field=models.IntegerField(default=4),
        ),
    ]
