# Generated by Django 2.2.12 on 2020-12-16 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0120_auto_20201216_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='quantity',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='Buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Buyer'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='image',
            field=models.ImageField(blank=True, default='null', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='price',
            field=models.FloatField(default=0.0, max_length=20),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product_name',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='store_name',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='seller',
            name='followers',
            field=models.IntegerField(default=68933),
        ),
        migrations.AlterField(
            model_name='storerating',
            name='randomImageNumber',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Product'),
        ),
    ]
