# Generated by Django 2.2.12 on 2020-12-17 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0130_auto_20201216_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingadd',
            old_name='shipping',
            new_name='User',
        ),
        migrations.AlterField(
            model_name='productrating',
            name='randomImageNumber',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='seller',
            name='followers',
            field=models.IntegerField(default=22693),
        ),
        migrations.AlterField(
            model_name='storerating',
            name='randomImageNumber',
            field=models.IntegerField(default=3),
        ),
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('transactions_id', models.IntegerField(default=80507806)),
                ('Buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Buyer')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
            ],
        ),
    ]
