# Generated by Django 2.2.12 on 2020-12-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0135_auto_20201217_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default='9DBB7C37CAB6B3AC323F', max_length=100),
        ),
        migrations.AlterField(
            model_name='seller',
            name='followers',
            field=models.IntegerField(default=39051),
        ),
    ]
