# Generated by Django 2.2.12 on 2020-12-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0152_auto_20201219_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='featured',
        ),
        migrations.AddField(
            model_name='product',
            name='advertise',
            field=models.CharField(choices=[('Not Promoted', 'Not Promoted'), ('Banner', 'Banner'), ('Pop Up', 'Pop Up'), ('Main Slidebar', 'Main Slidebar')], default='Not Promoted', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default='4DB037114CC7ABE58C6F', max_length=50),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='randomImageNumber',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='seller',
            name='followers',
            field=models.IntegerField(default=53958),
        ),
        migrations.AlterField(
            model_name='storerating',
            name='randomImageNumber',
            field=models.IntegerField(default=2),
        ),
    ]
