# Generated by Django 2.2.12 on 2020-12-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0162_auto_20201222_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotedproducts',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='promotedproducts',
            name='popup_image',
        ),
        migrations.RemoveField(
            model_name='promotedproducts',
            name='slideshow_image',
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default='17C2DFDC44FBD189574E', max_length=50),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='randomImageNumber',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='seller',
            name='followers',
            field=models.IntegerField(default=24056),
        ),
        migrations.AlterField(
            model_name='storerating',
            name='randomImageNumber',
            field=models.IntegerField(default=1),
        ),
    ]
