# Generated by Django 2.2.12 on 2020-11-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(default=59855, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productss',
            name='id',
            field=models.CharField(default=96509, max_length=10, primary_key=True, serialize=False),
        ),
    ]
