# Generated by Django 2.2.12 on 2020-11-26 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20201126_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(default=36137, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shippingadd',
            name='shipping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
