# Generated by Django 2.2.12 on 2020-12-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_lastlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastlogin',
            name='lougout',
            field=models.BooleanField(default=False),
        ),
    ]
