# Generated by Django 2.2.12 on 2020-12-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_remove_lastlogin_logout'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastlogin',
            name='logout',
            field=models.BooleanField(default=False),
        ),
    ]
