# Generated by Django 2.2.12 on 2020-12-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_auto_20201202_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Disable', 'Disable'), ('Enable', 'Enable')], default='Enable', max_length=10),
        ),
    ]
