# Generated by Django 2.2.12 on 2020-12-02 21:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_auto_20201202_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
