# Generated by Django 2.2.12 on 2020-12-02 21:20

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_auto_20201202_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productsss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('price', models.FloatField(default=0, max_length=10)),
                ('quantity', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('discount', models.FloatField(default=0, max_length=10)),
                ('category', models.CharField(choices=[('Motors', 'Motors'), ('Books, Movies & Music', 'Books, Movies & Music'), ('Electronics', 'Electronics'), ('Collectibles & Art', 'Collectibles & Art'), ('Fashion', 'Fashion'), ('Home & Garden', 'Home & Garden'), ('Sporting Goods', 'Sporting Goods'), ('Toys & Hobbies', 'Toys & Hobbies'), ('Business & Industrial', 'Business & Industrial'), ('Health & Beauty', 'Health & Beauty'), ('Others', 'Others')], default='null', max_length=100)),
                ('status', models.CharField(choices=[('Disable', 'Disable'), ('Enable', 'Enable')], default='Enable', max_length=10)),
                ('Seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Seller')),
            ],
        ),
    ]
