# Generated by Django 2.2.12 on 2020-12-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_auto_20201203_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, default='null', null=True, upload_to='imageUploads'),
        ),
    ]
