# Generated by Django 2.2.12 on 2020-12-05 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0054_auto_20201205_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Buyer'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
