# Generated by Django 2.2.12 on 2020-12-07 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_auto_20201205_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='name',
        ),
    ]
