# Generated by Django 2.2.12 on 2020-12-07 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0059_product_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='null', max_length=200)),
                ('body_text', django_ckeditor_5.fields.CKEditor5Field(default='null', verbose_name='product_description')),
                ('first_name', models.CharField(default='null', max_length=200)),
                ('last_name', models.CharField(default='null', max_length=200)),
                ('email', models.EmailField(default='null', max_length=200)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='contactBuyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='null', max_length=200)),
                ('body_text', django_ckeditor_5.fields.CKEditor5Field(default='null', verbose_name='product_description')),
                ('first_name', models.CharField(default='null', max_length=200)),
                ('last_name', models.CharField(default='null', max_length=200)),
                ('email', models.EmailField(default='null', max_length=200)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
