# Generated by Django 2.2.12 on 2020-12-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0061_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactseller',
            name='read_or_not',
            field=models.BooleanField(default=False),
        ),
    ]
