# Generated by Django 2.2.12 on 2020-12-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0069_auto_20201213_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
