# Generated by Django 2.2.12 on 2020-12-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0075_auto_20201213_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactseller',
            name='receivers',
            field=models.IntegerField(),
        ),
    ]
