# Generated by Django 2.2.12 on 2020-12-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0076_contactseller_receivers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactseller',
            name='receivers',
        ),
        migrations.AlterField(
            model_name='contactseller',
            name='receiver',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
