# Generated by Django 2.2.12 on 2020-12-13 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0079_auto_20201213_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactbuyer',
            name='receiver',
        ),
    ]
