# Generated by Django 2.2.12 on 2020-12-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0080_remove_contactbuyer_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactbuyer',
            name='receiver',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
