# Generated by Django 2.2.12 on 2020-12-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0081_contactbuyer_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactbuyer',
            name='receiver',
            field=models.IntegerField(default=0),
        ),
    ]
