# Generated by Django 2.2.12 on 2020-12-14 16:30

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0084_auto_20201213_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='null', max_length=200)),
                ('body_text', django_ckeditor_5.fields.CKEditor5Field(default='null', verbose_name='product_description')),
                ('first_name', models.CharField(default='null', max_length=200)),
                ('last_name', models.CharField(default='null', max_length=200)),
                ('email', models.EmailField(default='null', max_length=200)),
                ('read_or_not', models.BooleanField(default=False)),
            ],
        ),
    ]
