# Generated by Django 2.2.12 on 2020-12-14 16:34

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0086_contactsite_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsite',
            name='body_text',
            field=django_ckeditor_5.fields.CKEditor5Field(default='null', verbose_name='body_text'),
        ),
    ]
