# Generated by Django 2.2.12 on 2020-12-14 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0090_productrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='product',
            field=models.ForeignKey(default=50384, on_delete=django.db.models.deletion.CASCADE, to='store.Product'),
            preserve_default=False,
        ),
    ]
