# Generated by Django 2.2.12 on 2020-12-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0093_auto_20201214_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='image',
            field=models.ImageField(blank=True, default='null', null=True, upload_to=''),
        ),
    ]
