# Generated by Django 2.2.12 on 2020-12-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0095_auto_20201214_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='background_image',
            field=models.ImageField(blank=True, default='null', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='seller',
            name='followers',
            field=models.IntegerField(default=62563),
        ),
        migrations.AddField(
            model_name='seller',
            name='profile_image',
            field=models.ImageField(blank=True, default='null', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='seller',
            name='store_description',
            field=models.TextField(default='null', max_length=2000),
        ),
    ]
