# Generated by Django 2.2.12 on 2020-12-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0098_auto_20201215_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='randomImageNumber',
        ),
        migrations.AddField(
            model_name='storerating',
            name='randomImageNumber',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='seller',
            name='followers',
            field=models.IntegerField(default=72203),
        ),
    ]
