# Generated by Django 2.2.12 on 2020-12-16 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0104_auto_20201216_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='myshoplist',
            name='store_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.Seller'),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='randomImageNumber',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='seller',
            name='followers',
            field=models.IntegerField(default=18847),
        ),
    ]
