# Generated by Django 2.2.12 on 2020-12-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0108_auto_20201216_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myshoplist',
            name='image',
            field=models.CharField(blank=True, default='null', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='followers',
            field=models.IntegerField(default=85400),
        ),
        migrations.AlterField(
            model_name='storerating',
            name='randomImageNumber',
            field=models.IntegerField(default=3),
        ),
    ]
