# Generated by Django 2.2.12 on 2020-12-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0122_auto_20201216_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='followers',
            field=models.IntegerField(default=53412),
        ),
        migrations.AlterField(
            model_name='storerating',
            name='randomImageNumber',
            field=models.IntegerField(default=2),
        ),
    ]
