# Generated by Django 2.2.12 on 2020-12-16 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0125_auto_20201216_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='buyer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Buyer'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='followers',
            field=models.IntegerField(default=72474),
        ),
    ]
