# Generated by Django 2.2.12 on 2020-12-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0155_auto_20201220_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='mainMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_message', models.CharField(default='null', max_length=1000)),
                ('status', models.BooleanField(default=False)),
                ('title', models.CharField(default='null', max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default='2ED9B9A8967B556240DA', max_length=50),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='randomImageNumber',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='seller',
            name='followers',
            field=models.IntegerField(default=24025),
        ),
    ]
