# Generated by Django 2.2.12 on 2020-12-22 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0160_auto_20201222_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotedproducts',
            name='product_id',
        ),
        migrations.AddField(
            model_name='promotedproducts',
            name='product_banner',
            field=models.ForeignKey(default=50384, on_delete=django.db.models.deletion.CASCADE, to='store.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default='3CFBC635B22C992B96D5', max_length=50),
        ),
        migrations.AlterField(
            model_name='seller',
            name='followers',
            field=models.IntegerField(default=82028),
        ),
        migrations.AlterField(
            model_name='storerating',
            name='randomImageNumber',
            field=models.IntegerField(default=1),
        ),
    ]
